package Cafe;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JScrollBar;

/**
 *
 * @author shadman
 */
public class display_books extends javax.swing.JPanel {

    /**
     * Creates new form ManageBooksPanel
     */

    FoodView booklist = null;
    public display_books() {
        initComponents();
        set_genre_combo();
        update_list();
        JScrollBar verticalScrollBar = ScrollView.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
    }

    public void set_genre_combo() {
        cmb_genre.removeAll();
        cmb_genre.addItem("");
        try {
            Connection con = new DBConnection().getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT category FROM item_details");
            while (rs.next()) {
                cmb_genre.addItem(rs.getString("category"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void update_list() {
        String name = txt_name.getText();
//        String author = txt_author.getText();
        String genre = cmb_genre.getSelectedIndex() == -1 ? "" : cmb_genre.getItemAt(cmb_genre.getSelectedIndex());
        int price_from = txt_pricefrom.getText().equals("") ? 0 : Integer.parseInt(txt_pricefrom.getText());
        int price_to = txt_priceto.getText().equals("") ? 0 : Integer.parseInt(txt_priceto.getText());
        float rating_from = txt_ratingfrom.getText().equals("") ? 0.0f : Float.parseFloat(txt_ratingfrom.getText());
        float rating_to = txt_ratingto.getText().equals("") ? 0.0f : Float.parseFloat(txt_ratingto.getText());
//        int year_from = txt_yearfrom.getText().equals("")  ? 0 : Integer.parseInt(txt_yearfrom.getText());
//        int year_to = txt_yearto.getText().equals("") ? 0 : Integer.parseInt(txt_yearto.getText());

        var books = new ArrayList<Food>();

        try {
            Connection con = new DBConnection().getConnection();
            String query = "SELECT * FROM item_details WHERE item_name LIKE ? AND category LIKE ? AND price BETWEEN ? AND ? AND item_rating BETWEEN ? AND ?";
            var st = con.prepareStatement(query);
            st.setString(1, name.equals("") ? "%" : "%"+name+"%");
//            st.setString(2, author.equals("") ? "%" : "%"+author+"%");
            st.setString(2, genre.equals("") ? "%" : "%"+genre+"%");
            st.setInt(3, price_from);
            st.setInt(4, price_to == 0 ? 999999999 : price_to);
            st.setFloat(5, rating_from);
            st.setFloat(6, rating_to == 0 ? 9 : rating_to);
//            st.setInt(8, year_from);
//            st.setInt(9, year_to == 0 ? 99999 : year_to);

            var rs = st.executeQuery();
            while (rs.next()) {
                books.add(new Food(rs));
            }
            update_res_panel(new FoodView(books));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    public void update_res_panel(FoodView bv) {
        if (booklist != null) ScrollView.getViewport().remove(booklist);
        ScrollView.getViewport().add(bv);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_search = new necesario.RSMaterialButtonCircle();
        txt_name = new app.bolivia.swing.JCTextField();
        txt_ratingfrom = new app.bolivia.swing.JCTextField();
        txt_ratingto = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_pricefrom = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_priceto = new app.bolivia.swing.JCTextField();
        cmb_genre = new javax.swing.JComboBox<>();
        ScrollView = new javax.swing.JScrollPane();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 760));
        setPreferredSize(new java.awt.Dimension(1500, 780));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Category");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("rating");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Glass Antiqua", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        btn_search.setBackground(new java.awt.Color(0, 0, 0));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-64 white.png"))); // NOI18N
        btn_search.setText("Search");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel2.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 130, 50));

        txt_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_name.setPlaceholder("Item Name");
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 350, 30));

        txt_ratingfrom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_ratingfrom.setPlaceholder("From Rating");
        jPanel2.add(txt_ratingfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 150, 30));

        txt_ratingto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_ratingto.setPlaceholder("To Rating");
        jPanel2.add(txt_ratingto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 150, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Glass Antiqua", 0, 24)); // NOI18N
        jLabel9.setText("-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 10, -1));

        txt_pricefrom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_pricefrom.setPlaceholder("From Price");
        jPanel2.add(txt_pricefrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 150, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Glass Antiqua", 0, 24)); // NOI18N
        jLabel10.setText("-");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 10, -1));

        txt_priceto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txt_priceto.setPlaceholder("To Price");
        jPanel2.add(txt_priceto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 150, 30));

        jPanel2.add(cmb_genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 330, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 160));

        ScrollView.setBackground(new java.awt.Color(255, 255, 255));
        ScrollView.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        add(ScrollView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1500, 570));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hamburger.png"))); // NOI18N
        jLabel8.setText("       M   E   N   U");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 350, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 5, 50, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 0, 60, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 5, 60, 40));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        update_list();
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        UserPage up = new UserPage();
        up.setVisible(true);
        MainMenu mn = new MainMenu();
        mn.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollView;
    private necesario.RSMaterialButtonCircle btn_search;
    private javax.swing.JComboBox<String> cmb_genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private app.bolivia.swing.JCTextField txt_name;
    private app.bolivia.swing.JCTextField txt_pricefrom;
    private app.bolivia.swing.JCTextField txt_priceto;
    private app.bolivia.swing.JCTextField txt_ratingfrom;
    private app.bolivia.swing.JCTextField txt_ratingto;
    // End of variables declaration//GEN-END:variables
}
