/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cafe;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nahia
 */
public class ManageItems extends javax.swing.JFrame {

    /**
     * Creates new form ManageMenu
     */
    String iname, cat;
    String path2 = null;
    int id, price;
    DefaultTableModel model;
    public ManageItems() {
        initComponents();
        setItemDetailsToTable();
    }
    
    public void update_table() {
        DefaultTableModel dtm = (DefaultTableModel) tbl_itemDetails.getModel();
        dtm.setRowCount(0);
    }
    
    //to delete a record
    public void deleteRecord(String s) {
        try {
            if(s.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please select an Item to delete");
                return;
            }
            Connection con = new DBConnection().getConnection();
            String query = "delete from item_details where item_id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, s);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "A record has been deleted successfully");
        } catch(Exception e) {
            e.printStackTrace();
        }
        update_table();
        setItemDetailsToTable();
    }
    
    //to set the item details
    public void setItemDetailsToTable() {
        try{
            Connection con = new DBConnection().getConnection();
            String sql = "select * from item_details";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()) {
                String itemID = rs.getString("item_id");
                String itemName = rs.getString("item_name");
                String cat = rs.getString("category");
                int pr = rs.getInt("price");
                
                Object[] obj = {itemID, itemName, cat, pr};
                model = (DefaultTableModel) tbl_itemDetails.getModel();
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panel1 = new java.awt.Panel();
        jLabel12 = new javax.swing.JLabel();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCTextField3 = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCTextField4 = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCTextField5 = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_itemDetails = new rojeru_san.complementos.RSTableMetro();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(228, 95, 97));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jCTextField2.setBackground(new java.awt.Color(228, 95, 97));
        jCTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jCTextField2.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField2.setPlaceholder("Enter Item ID");
        jCTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField2ActionPerformed(evt);
            }
        });
        panel1.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 320, 40));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Item ID");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ID.png"))); // NOI18N
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, 40));

        jCTextField3.setBackground(new java.awt.Color(228, 95, 97));
        jCTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jCTextField3.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField3.setPlaceholder("Enter Item Name");
        jCTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField3ActionPerformed(evt);
            }
        });
        panel1.add(jCTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 320, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 120, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/items30px.png"))); // NOI18N
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 30, 40));

        jCTextField4.setBackground(new java.awt.Color(228, 95, 97));
        jCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jCTextField4.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField4.setPlaceholder("Enter Item Category");
        jCTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField4ActionPerformed(evt);
            }
        });
        panel1.add(jCTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 320, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Category");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 30, 40));

        jCTextField5.setBackground(new java.awt.Color(228, 95, 97));
        jCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jCTextField5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jCTextField5.setPhColor(new java.awt.Color(255, 255, 255));
        jCTextField5.setPlaceholder("Enter Item Price");
        jCTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField5ActionPerformed(evt);
            }
        });
        panel1.add(jCTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 320, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ImageIcon.png"))); // NOI18N
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 40, 50));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 120, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Image");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 120, 30));

        lbl_photo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_photo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_photo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        panel1.add(lbl_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 160, 160));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 680, 120, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/price.png"))); // NOI18N
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 30, 40));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPLOAD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 120, 50));

        jButton4.setBackground(new java.awt.Color(102, 102, 255));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 680, 120, 50));

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ADD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 120, 50));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 780));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 95, 97));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 40, -1));

        tbl_itemDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Name", "Category", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_itemDetails.setColorBackgoundHead(new java.awt.Color(228, 95, 97));
        tbl_itemDetails.setColorBordeFilas(new java.awt.Color(228, 95, 97));
        tbl_itemDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_itemDetails.setColorFilasForeground1(new java.awt.Color(228, 95, 97));
        tbl_itemDetails.setColorFilasForeground2(new java.awt.Color(228, 95, 97));
        tbl_itemDetails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        tbl_itemDetails.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        tbl_itemDetails.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_itemDetails.setFuenteHead(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        tbl_itemDetails.setRowHeight(40);
        tbl_itemDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_itemDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_itemDetails);
        if (tbl_itemDetails.getColumnModel().getColumnCount() > 0) {
            tbl_itemDetails.getColumnModel().getColumn(0).setResizable(false);
            tbl_itemDetails.getColumnModel().getColumn(1).setResizable(false);
            tbl_itemDetails.getColumnModel().getColumn(2).setResizable(false);
            tbl_itemDetails.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 880, 580));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Edit_Property_50px.png"))); // NOI18N
        jLabel7.setText("   Manage Items");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 350, 60));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 440, 5));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 950, 780));

        setSize(new java.awt.Dimension(1500, 780));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        HomePage lgm = new HomePage();
        lgm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2ActionPerformed

    private void jCTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField3ActionPerformed

    private void jCTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField4ActionPerformed

    private void jCTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lbl_photo.setIcon(icon);
            path2 = path;
        } catch (IOException ex) {
            Logger.getLogger(ManageItems.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String s = jCTextField2.getText();
        deleteRecord(s);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id = jCTextField2.getText();
        String name = jCTextField3.getText();
        String cat = jCTextField4.getText();
        String price = jCTextField5.getText();
        if(id.isEmpty() || name.isEmpty() || cat.isEmpty() || price.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Fill all the credential");
            return;
        }
        String s = "INSERT INTO item_details (item_id, item_name, category, price, item_picture) VALUES (?, ?, ?, ?, ?)";
        try {
            Connection con = new DBConnection().getConnection();
            PreparedStatement pst = con.prepareStatement(s);
            pst.setInt(1, Integer.parseInt(id));
            pst.setString(2, name);
            pst.setString(3, cat);
            pst.setInt(4, Integer.parseInt(price));
//            if(path2 == null) {
//            pst.execute();
//                JOptionPane.showMessageDialog(null, "Please select an Image");
//                return;
//            }
            InputStream is = new FileInputStream(new File(path2));
            pst.setBlob(5, is);
            pst.execute();
            jCTextField2.setText("");
            jCTextField3.setText("");
            jCTextField4.setText("");
            jCTextField5.setText("");
            lbl_photo.setIcon(null);
            JOptionPane.showMessageDialog(null, "Data Saved Successfully");
        } catch (Exception e) {
            e.printStackTrace();
        }
        update_table();
        setItemDetailsToTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void tbl_itemDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_itemDetailsMouseClicked
        // TODO add your handling code here:
        int rowNo = tbl_itemDetails.getSelectedRow();
        String click = (tbl_itemDetails.getModel().getValueAt(rowNo, 0).toString());
        String sql = "select * from item_details where item_id='" + click + "'";
        try {
            Connection con = new DBConnection().getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if(rs.next()) {
                String id = Integer.toString(rs.getInt(1));
                String name = rs.getString(2);
                String category = rs.getString(3);
                String price = Integer.toString(rs.getInt(4));
                Blob image = (Blob) rs.getBlob(5);
                String path = "D:\\Java Project Academic\\CafeHubFinal\\src\\tempImage\\img.jpg";
                byte [] bytea = image.getBytes(1, (int)image.length());
                FileOutputStream fos = new FileOutputStream(path);
                fos.write(bytea);
                BufferedImage bi = ImageIO.read(new File(path));
                Image img = bi.getScaledInstance(160, 160, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);
                lbl_photo.setIcon(icon);
                
                jCTextField2.setText(id);
                jCTextField3.setText(name);
                jCTextField4.setText(category);
                jCTextField5.setText(price);
            }
        }  catch (Exception e) {
                    e.printStackTrace();
        }
//        TableModel model = tbl_itemDetails.getModel();
//        
//        jCTextField2.setText(model.getValueAt(rowNo, 0).toString());
//        jCTextField3.setText(model.getValueAt(rowNo, 1).toString());
//        jCTextField4.setText(model.getValueAt(rowNo, 2).toString());
//        jCTextField5.setText(model.getValueAt(rowNo, 3).toString());
//        Blob image = rs.getBlob(4);
    }//GEN-LAST:event_tbl_itemDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private app.bolivia.swing.JCTextField jCTextField2;
    private app.bolivia.swing.JCTextField jCTextField3;
    private app.bolivia.swing.JCTextField jCTextField4;
    private app.bolivia.swing.JCTextField jCTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_photo;
    private java.awt.Panel panel1;
    private rojeru_san.complementos.RSTableMetro tbl_itemDetails;
    // End of variables declaration//GEN-END:variables
}
