/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cafe;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nahia
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    Color mouseEnterColor = new Color(0, 0, 0);
    Color mouseExitColor = new Color(77,75,86);
    DefaultTableModel model;
    public UserPage() {
        initComponents();
        jLabel2.setText("User");
        show(position);
//        jScrollPane3.getVerticalScrollBar().setUnitIncrement(25);
        JScrollBar verticalScrollBar = jScrollPane3.getVerticalScrollBar();
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setBlockIncrement(200);
    }
    int position = 0;
    public String[] takeimage() {
        String[] Images = {
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Brown_Back.jpg",//0
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\iceCream.jpg", //1
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Barbecue Buffalo Wings.png", //2
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Barbecue Ribs.png", //3
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Breakfast Sandwich.png", //4
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Southern Fried Chicken.png", //5
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Chicken Parmesan Hero.png", //6
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Creole Soul Chicken.png", //7
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Grilled Lemon Herb Chicken Salad.png", //8
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\Teriyaki Chicken Bowl.png", //9
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\pancake.png", //10
            "D:\\Java Project Academic\\CafeHubFinal\\src\\imagespath\\pizza.png"
        };
        return Images;
    }
    
    public void show(int index) {
        String[] Images = takeimage();
        ImageIcon icon = new ImageIcon(Images[index]);
        Image image = icon.getImage().getScaledInstance(580, 330, Image.SCALE_SMOOTH);
        lbl.setIcon(new ImageIcon(image));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel50 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel48 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        previous = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 95, 97));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 40));

        jPanel2.setBackground(new java.awt.Color(77, 75, 86));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 5, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 160, 60));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CafeHub");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 0, 30, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 60));

        jPanel3.setBackground(new java.awt.Color(77, 75, 86));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(77, 75, 86));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        jLabel6.setText("   About Us");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 60));

        jPanel7.setBackground(new java.awt.Color(77, 75, 86));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel8.setText("    Manage User");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 340, 60));

        jPanel5.setBackground(new java.awt.Color(87, 151, 225));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("    Home");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 180, 60));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 340, 60));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Features");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 30));

        jPanel6.setBackground(new java.awt.Color(77, 75, 86));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        jLabel7.setText("    Main Menu");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 60));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 340, 60));

        jPanel8.setBackground(new java.awt.Color(77, 75, 86));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/globe.png"))); // NOI18N
        jLabel9.setText("    Order Online");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 220, 60));

        jPanel9.setBackground(new java.awt.Color(77, 75, 86));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel10.setText("    Manage User");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 340, 60));

        jPanel10.setBackground(new java.awt.Color(77, 75, 86));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel11.setText("    Gift Cards");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 60));

        jPanel11.setBackground(new java.awt.Color(77, 75, 86));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel13.setText("    Manage User");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 340, 60));

        jPanel12.setBackground(new java.awt.Color(228, 95, 97));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px.png"))); // NOI18N
        jLabel14.setText("    Log Out");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 60));

        jPanel13.setBackground(new java.awt.Color(77, 75, 86));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel15.setText("    Manage User");
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 340, 60));

        jPanel14.setBackground(new java.awt.Color(77, 75, 86));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gallery.png"))); // NOI18N
        jLabel16.setText("    Gallery");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel14.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 190, 60));

        jPanel15.setBackground(new java.awt.Color(77, 75, 86));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel17.setText("    Manage User");
        jPanel15.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 340, 60));

        jPanel18.setBackground(new java.awt.Color(77, 75, 86));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_mode.png"))); // NOI18N
        jLabel20.setText("    Switch Dark Mode");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        jPanel18.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        jPanel19.setBackground(new java.awt.Color(77, 75, 86));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel21.setText("    Manage User");
        jPanel19.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 340, 60));

        jPanel23.setBackground(new java.awt.Color(77, 75, 86));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact.png"))); // NOI18N
        jLabel30.setText("    Contact Us");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });
        jPanel23.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 230, 60));

        jPanel24.setBackground(new java.awt.Color(77, 75, 86));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        jLabel31.setText("    Manage User");
        jPanel24.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 190, 60));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 60));

        jPanel3.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 340, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 720));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel16.setBackground(new java.awt.Color(247, 247, 247));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 100)); // NOI18N
        jLabel18.setText("H U B");
        jPanel16.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 260, 120));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 40)); // NOI18N
        jLabel23.setText("Comfort Food");
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 240, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cafe.png"))); // NOI18N
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 110, 150));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 100)); // NOI18N
        jLabel19.setText("C A F E");
        jPanel16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 340, 140));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG Panel.jpg"))); // NOI18N
        jPanel16.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 720));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel4.png"))); // NOI18N
        jPanel17.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 880, 200, 200));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel1.png"))); // NOI18N
        jPanel20.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        jPanel16.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 880, 200, 200));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Panel2.png"))); // NOI18N
        jPanel21.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        jPanel16.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 880, 200, 200));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel3.png"))); // NOI18N
        jPanel22.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        jPanel16.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 880, 200, 200));

        jPanel26.setBackground(new java.awt.Color(155, 61, 27));
        jPanel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ORDER NOW");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });
        jPanel26.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 3, 120, 40));

        jPanel16.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1140, 170, 50));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel66.setText("DELIVERY EXPANDED");
        jPanel27.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 220, 30));

        jLabel45.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 60)); // NOI18N
        jLabel45.setText("ORDER");
        jPanel27.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 200, -1));

        jPanel31.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel27.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 380, 1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pizza.png"))); // NOI18N
        jPanel27.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 530));

        jLabel67.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(155, 61, 27));
        jLabel67.setText("pick-up & delivery");
        jPanel27.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, 30));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Postmates, GrubHub, Seamless & UberEats");
        jPanel27.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 300, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("please order via Square.");
        jPanel27.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, -1));

        jLabel68.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel68.setText("CONTACTLESS TAKE-OUT");
        jPanel27.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, 30));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("To place an order for pickup,");
        jPanel27.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, -1));

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("To place an order for delivery, please choose from");
        jPanel27.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 350, -1));

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("one of our partners below:");
        jPanel27.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 220, -1));

        jPanel28.setBackground(new java.awt.Color(155, 61, 27));
        jPanel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel28.setForeground(new java.awt.Color(255, 255, 255));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("ORDER PICKUP");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel38MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel38MouseExited(evt);
            }
        });
        jPanel28.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jPanel27.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 130, 40));

        jPanel16.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1690, -1, 530));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pancake.png"))); // NOI18N
        jPanel29.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 620));

        jLabel41.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 60)); // NOI18N
        jLabel41.setText("ABOUT");
        jPanel29.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 200, -1));

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(155, 61, 27));
        jLabel42.setText("PHONE");
        jPanel29.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 70, 30));

        jPanel30.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 182, 380, 1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/message.png"))); // NOI18N
        jPanel29.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 30, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phone.png"))); // NOI18N
        jPanel29.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 30, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location.png"))); // NOI18N
        jPanel29.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 30, -1));

        jLabel55.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(155, 61, 27));
        jLabel55.setText("   our service");
        jPanel29.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 130, 30));

        jLabel56.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(155, 61, 27));
        jLabel56.setText("Monday - 12pm-9pm");
        jPanel29.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 190, 30));

        jLabel57.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(155, 61, 27));
        jLabel57.setText("01783928393");
        jPanel29.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 110, 30));

        jLabel58.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(155, 61, 27));
        jLabel58.setText("Tuesday - 12pm-9pm");
        jPanel29.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 160, 30));

        jLabel59.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(155, 61, 27));
        jLabel59.setText("Wednesday - 12pm-9pm");
        jPanel29.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 190, 30));

        jLabel60.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(155, 61, 27));
        jLabel60.setText("Friday - 12pm-9pm");
        jPanel29.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 190, 30));

        jLabel61.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(155, 61, 27));
        jLabel61.setText("Saturday - 12pm-9pm");
        jPanel29.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 190, 30));

        jLabel62.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(155, 61, 27));
        jLabel62.setText("Sunday - 12pm-9pm");
        jPanel29.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 160, 30));

        jLabel63.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(155, 61, 27));
        jLabel63.setText("HOURS");
        jPanel29.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 80, 30));

        jLabel64.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(155, 61, 27));
        jLabel64.setText("Thursday - 12pm-9pm");
        jPanel29.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 190, 30));

        jLabel65.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(155, 61, 27));
        jLabel65.setText("01756737342");
        jPanel29.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 110, 30));

        jPanel16.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2750, 1160, 620));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cow.png"))); // NOI18N
        jPanel32.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 22, 150, 120));

        jLabel71.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(155, 61, 27));
        jLabel71.setText("restaurant... EVER\"");
        jPanel32.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 30));

        jLabel74.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(155, 61, 27));
        jLabel74.setText("\"Best vegetarian");
        jPanel32.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 30));

        jScrollPane4.setBorder(null);
        jScrollPane4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea3.setRows(5);
        jTextArea3.setText("Very nice, cozy place. Service was good, \n food delicious and so much to choose \n   from :) Wanna go there again :) \n\n    Pros: Good price, Good food, Cozy \n                  place and nice staff");
        jTextArea3.setBorder(null);
        jTextArea3.setFocusable(false);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel32.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 290, 140));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/double quote.png"))); // NOI18N
        jPanel32.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, 40));

        jPanel16.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 2260, 360, 450));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yelp.png"))); // NOI18N
        jPanel33.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 22, -1, -1));

        jLabel69.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(155, 61, 27));
        jLabel69.setText("expectations!\"");
        jPanel33.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 30));

        jLabel72.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(155, 61, 27));
        jLabel72.setText("\"It surpassed all my");
        jPanel33.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 190, 30));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("The food looks like it has been prepared \nfor a culinary magazine. While in New York\nCity add CafeHub as a culinary experience. \nIt will be a good place to take a date to or\n           gettogetherwith some friends. \n           You will not be disappointed.\n");
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel33.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 290, 140));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/double quote.png"))); // NOI18N
        jPanel33.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, 40));

        jPanel16.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2260, 360, 450));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bird.png"))); // NOI18N
        jPanel34.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 22, 150, 127));

        jLabel70.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(155, 61, 27));
        jLabel70.setText("good prices\"");
        jPanel34.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, 30));

        jLabel73.setFont(new java.awt.Font("Yu Gothic UI", 0, 22)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(155, 61, 27));
        jLabel73.setText("\"Delicious food,");
        jPanel34.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 170, 30));

        jScrollPane2.setBorder(null);
        jScrollPane2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea2.setRows(5);
        jTextArea2.setText("I absolutely love this place. The Wings \nare the best things ever!!! I've been a \nveggie for 22 years now and never had \nwings, Philly Cheese steak etc so to get \nall this as a veggie option is fantastic! \n        I go to this place every time \n               I'm in New York :)");
        jTextArea2.setBorder(null);
        jTextArea2.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel34.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 290, 140));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/double quote.png"))); // NOI18N
        jPanel34.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 50, 40));

        jPanel16.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 2260, 360, 450));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel35.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 580, 330));

        next.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 100)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px_1.png"))); // NOI18N
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        jPanel35.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 50, 60));

        previous.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 100)); // NOI18N
        previous.setForeground(new java.awt.Color(255, 255, 255));
        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousMouseClicked(evt);
            }
        });
        jPanel35.add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, 60));

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GalleryBG.png"))); // NOI18N
        jPanel35.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 330));

        jPanel16.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1320, 1160, 330));

        jPanel36.setBackground(new java.awt.Color(247, 247, 247));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Yu Gothic UI", 1, 100)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(155, 61, 27));
        jLabel52.setText(". . .");
        jPanel36.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 70, 90));

        jLabel51.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(155, 61, 27));
        jLabel51.setText("GALLERY");
        jPanel36.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 160, 50));

        jPanel16.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1220, 250, 100));

        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/instagram.png"))); // NOI18N
        jPanel37.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 50, 50));

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/twitter.png"))); // NOI18N
        jPanel37.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 50, 50));

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook.png"))); // NOI18N
        jPanel37.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 50, 50));

        jLabel53.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("connect with us");
        jPanel37.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 330, 90));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG Res.png"))); // NOI18N
        jPanel37.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, -1));

        jPanel16.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3400, 1160, 490));

        jScrollPane3.setViewportView(jPanel16);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 1160, 720));

        setSize(new java.awt.Dimension(1500, 780));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jPanel6.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Light Mode") {
            Color cl = new Color(51, 51, 51);
            jPanel6.setBackground(cl);
        }else
        jPanel6.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        jPanel8.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        jPanel10.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        jPanel14.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jPanel4.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        // TODO add your handling code here:
        jPanel23.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
        jPanel18.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Light Mode") {
            Color cl = new Color(51, 51, 51);
            jPanel8.setBackground(cl);
        }else jPanel8.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Light Mode") {
            Color cl = new Color(51, 51, 51);
            jPanel10.setBackground(cl);
        }else
        jPanel10.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Light Mode") {
            Color cl = new Color(51, 51, 51);
            jPanel14.setBackground(cl);
        }else
        jPanel14.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Light Mode") {
            Color cl = new Color(51, 51, 51);
            jPanel4.setBackground(cl);
        }else
        jPanel4.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Light Mode") {
            Color cl = new Color(51, 51, 51);
            jPanel23.setBackground(cl);
        }else
        jPanel23.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Light Mode") {
            Color cl = new Color(51, 51, 51);
            jPanel18.setBackground(cl);
        }else
        jPanel18.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        Color c = new Color(87,151,225);
        jPanel5.setBackground(c);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jPanel5.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jPanel12.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        Color c = new Color(228,95,97);
        jPanel12.setBackground(c);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        MainMenu mn = new MainMenu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Admin_login al = new Admin_login();
        al.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        String s = jLabel20.getText();
        if(s == "    Switch Dark Mode") {
            jLabel20.setText("    Switch Light Mode");
            Color cl = new Color(51, 51, 51);
            jPanel3.setBackground(cl);
            jPanel6.setBackground(cl);
            jPanel8.setBackground(cl);
            jPanel10.setBackground(cl);
            jPanel14.setBackground(cl);
            jPanel4.setBackground(cl);
            jPanel23.setBackground(cl);
            jPanel18.setBackground(cl);
            Color cll = new Color(77,75,86);
            jPanel16.setBackground(cll);
            jPanel1.setBackground(cl);
//            Color f = new Color(255, 255, 255);
//            jLabel19.setForeground(f);
//            jLabel29.setForeground(f);
//            jLabel27.setForeground(f);
//            jLabel25.setForeground(f);
//            jLabel23.setForeground(f);
//            jLabel28.setForeground(f);
        } else {
            jLabel20.setText("    Switch Dark Mode");
            Color cl = new Color(77,75,86);
            jPanel3.setBackground(cl);
            jPanel6.setBackground(cl);
            jPanel8.setBackground(cl);
            jPanel10.setBackground(cl);
            jPanel14.setBackground(cl);
            jPanel4.setBackground(cl);
            jPanel23.setBackground(cl);
            jPanel18.setBackground(cl);
            Color cll = new Color(204,204,204);
            jPanel16.setBackground(cll);
            Color f = new Color(228,95,97);
            jPanel1.setBackground(f);
//            Color f = new Color(102,102,102);
//            jLabel19.setForeground(f);
//            jLabel29.setForeground(f);
//            jLabel27.setForeground(f);
//            jLabel25.setForeground(f);
//            jLabel23.setForeground(f);
//            jLabel28.setForeground(f);
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        // TODO add your handling code here:
        new Thread();
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(UserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p = this.lbl.getX();
        
        if(p > -1) {
            Animacion.Animacion.mover_izquierda(900, 200, 1, 2, lbl);
        }
        int n = takeimage().length;
        position = (position + 1) % n;
//        if(position >= takeimage().length) {
//            position = takeimage().length - 1;
//        } 
        show(position);
    }//GEN-LAST:event_nextMouseClicked

    private void previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMouseClicked
        // TODO add your handling code here:
        new Thread();
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(UserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        int p = this.lbl.getX();
        
        if(p > -1) {
            Animacion.Animacion.mover_izquierda(900, 200, 1, 2, lbl);
        }
        int n = takeimage().length;
        position = (position - 1);
        position = Math.abs(position);
        position = position % n;
//        if(position < 0) {
//            position = 0;
//        }
        show(position);
    }//GEN-LAST:event_previousMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        Gallery g = new Gallery();
        g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        // TODO add your handling code here:
        Color rd = new Color(144, 44, 6);
        jPanel26.setBackground(rd);
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        // TODO add your handling code here:
        Color m = new Color(155,61,27);
        jPanel26.setBackground(m);
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        OrderOnline oo = new OrderOnline();
        oo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel38MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseExited
        // TODO add your handling code here:
        Color m = new Color(155,61,27);
        jPanel28.setBackground(m);
    }//GEN-LAST:event_jLabel38MouseExited

    private void jLabel38MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseEntered
        // TODO add your handling code here:
        Color rd = new Color(144, 44, 6);
        jPanel28.setBackground(rd);
    }//GEN-LAST:event_jLabel38MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel next;
    private javax.swing.JLabel previous;
    // End of variables declaration//GEN-END:variables
}
